# Generated by Django 3.2.18 on 2023-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_ids',
            field=models.ManyToManyField(related_name='movie_genre', to='movie.Genre'),
        ),
    ]
