# Generated by Django 3.2.18 on 2023-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_keyword',
            field=models.ManyToManyField(related_name='movies', to='movie.Keyword'),
        ),
    ]
