# Generated by Django 3.2.18 on 2023-05-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20230518_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='keyword_id',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
