# Generated by Django 3.2.18 on 2023-05-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20230518_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='translated',
            field=models.TextField(null=True),
        ),
    ]
