
UPDATE movie_keyword SET translated = '운송' WHERE id=396;
UPDATE movie_keyword SET translated = '예언' WHERE id=530;
UPDATE movie_keyword SET translated = '미국 남부' WHERE id=531;
UPDATE movie_keyword SET translated = '사랑하는 사람의 상실' WHERE id=697;
UPDATE movie_keyword SET translated = '형사' WHERE id=703;
UPDATE movie_keyword SET translated = '마샬 아츠' WHERE id=779;
UPDATE movie_keyword SET translated = '어쎄신' WHERE id=782;
UPDATE movie_keyword SET translated = '원작 소설' WHERE id=818;
UPDATE movie_keyword SET translated = '영화 사업' WHERE id=886;
UPDATE movie_keyword SET translated = '애기' WHERE id=1009;
UPDATE movie_keyword SET translated = '위장 신분' WHERE id=1308;
UPDATE movie_keyword SET translated = '돌격소총' WHERE id=1376;
UPDATE movie_keyword SET translated = '글레디에이터' WHERE id=1527;
UPDATE movie_keyword SET translated = '스탠드오프' WHERE id=1666;
UPDATE movie_keyword SET translated = '히어로' WHERE id=1701;
UPDATE movie_keyword SET translated = '동굴' WHERE id=1964;
UPDATE movie_keyword SET translated = '산타클로스' WHERE id=1991;
UPDATE movie_keyword SET translated = '안티히어로' WHERE id=2095;
UPDATE movie_keyword SET translated = '말' WHERE id=2673;
UPDATE movie_keyword SET translated = '애로 배우' WHERE id=2727;
UPDATE movie_keyword SET translated = '복싱' WHERE id=2792;
UPDATE movie_keyword SET translated = '치어리더' WHERE id=2920;
UPDATE movie_keyword SET translated = '악몽' WHERE id=3030;
UPDATE movie_keyword SET translated = '갱스터' WHERE id=3149;
UPDATE movie_keyword SET translated = '남자 우정' WHERE id=3230;
UPDATE movie_keyword SET translated = '신부' WHERE id=3582;
UPDATE movie_keyword SET translated = '희생자' WHERE id=4399;
UPDATE movie_keyword SET translated = '포스트아포칼립스' WHERE id=4458;
UPDATE movie_keyword SET translated = '트레이닝' WHERE id=4613;
UPDATE movie_keyword SET translated = '약탈' WHERE id=4631;
UPDATE movie_keyword SET translated = '낙하산' WHERE id=4679;
UPDATE movie_keyword SET translated = '외계 생명체' WHERE id=4862;
UPDATE movie_keyword SET translated = '쉘터' WHERE id=4917;
UPDATE movie_keyword SET translated = '코드' WHERE id=4950;
UPDATE movie_keyword SET translated = '세계 챔피언' WHERE id=5378;
UPDATE movie_keyword SET translated = '인물 전기' WHERE id=5565;
UPDATE movie_keyword SET translated = '숲' WHERE id=5774;
UPDATE movie_keyword SET translated = '경찰' WHERE id=6149;
UPDATE movie_keyword SET translated = '격리' WHERE id=6898;
UPDATE movie_keyword SET translated = '금발' WHERE id=6946;
UPDATE movie_keyword SET translated = '바질란테' WHERE id=7002;
UPDATE movie_keyword SET translated = '쿠웨이트' WHERE id=8651;
UPDATE movie_keyword SET translated = '속편' WHERE id=9663;
UPDATE movie_keyword SET translated = '슈퍼히어로' WHERE id=9715;
UPDATE movie_keyword SET translated = '만화원작' WHERE id=9717;
UPDATE movie_keyword SET translated = '숲' WHERE id=9720;
UPDATE movie_keyword SET translated = '범죄조직 보스' WHERE id=9730;
UPDATE movie_keyword SET translated = '복수' WHERE id=9748;
UPDATE movie_keyword SET translated = '사회적 부적응자' WHERE id=9789;
UPDATE movie_keyword SET translated = '살인자' WHERE id=9826;
UPDATE movie_keyword SET translated = '초자연적' WHERE id=9853;
UPDATE movie_keyword SET translated = '멸망' WHERE id=10150;
UPDATE movie_keyword SET translated = '저주' WHERE id=10541;
UPDATE movie_keyword SET translated = '자연재해' WHERE id=10617;
UPDATE movie_keyword SET translated = '새로운 시대' WHERE id=10683;
UPDATE movie_keyword SET translated = '스파이활동' WHERE id=11134;
UPDATE movie_keyword SET translated = '의인화' WHERE id=11477;
UPDATE movie_keyword SET translated = '총격전' WHERE id=12371;
UPDATE movie_keyword SET translated = '추리극' WHERE id=12570;
UPDATE movie_keyword SET translated = '로스엔젤레스, 캘리포니아' WHERE id=12670;
UPDATE movie_keyword SET translated = '유아' WHERE id=13014;
UPDATE movie_keyword SET translated = '여름' WHERE id=13088;
UPDATE movie_keyword SET translated = '라스베가스' WHERE id=14570;
UPDATE movie_keyword SET translated = '총사' WHERE id=14577;
UPDATE movie_keyword SET translated = '두더지' WHERE id=14617;
UPDATE movie_keyword SET translated = '싸움' WHERE id=14955;
UPDATE movie_keyword SET translated = '악마' WHERE id=15001;
UPDATE movie_keyword SET translated = '상어' WHERE id=15097;
UPDATE movie_keyword SET translated = '이혼' WHERE id=15160;
UPDATE movie_keyword SET translated = '소대' WHERE id=15240;
UPDATE movie_keyword SET translated = '십대 소년' WHERE id=18068;
UPDATE movie_keyword SET translated = '그래픽 노블' WHERE id=18712;
UPDATE movie_keyword SET translated = '성인' WHERE id=155477;
UPDATE movie_keyword SET translated = '호송' WHERE id=155499;
UPDATE movie_keyword SET translated = '증오' WHERE id=158449;
UPDATE movie_keyword SET translated = '도발적인 운전' WHERE id=159931;
UPDATE movie_keyword SET translated = '관음' WHERE id=163957;
UPDATE movie_keyword SET translated = '맹인' WHERE id=164092;
UPDATE movie_keyword SET translated = '외톨이' WHERE id=167104;
UPDATE movie_keyword SET translated = '2인조 경찰' WHERE id=167316;
UPDATE movie_keyword SET translated = '판타지세계' WHERE id=170362;
UPDATE movie_keyword SET translated = '섹스코메디' WHERE id=170827;
UPDATE movie_keyword SET translated = '신분세탁' WHERE id=177035;
UPDATE movie_keyword SET translated = '다크 판타지' WHERE id=177895;
UPDATE movie_keyword SET translated = '쿠키영상' WHERE id=179430;
UPDATE movie_keyword SET translated = '쿠키영상' WHERE id=179431;
UPDATE movie_keyword SET translated = '마블' WHERE id=180547;
UPDATE movie_keyword SET translated = '토끼애니메이션' WHERE id=181140;
UPDATE movie_keyword SET translated = '저주인형' WHERE id=183963;
UPDATE movie_keyword SET translated = '미스터 캣' WHERE id=186811;
UPDATE movie_keyword SET translated = '여성감독' WHERE id=187056;
UPDATE movie_keyword SET translated = '터널' WHERE id=189102;
UPDATE movie_keyword SET translated = '정의' WHERE id=193946;
UPDATE movie_keyword SET translated = '껍데기' WHERE id=194258;
UPDATE movie_keyword SET translated = '앵무새' WHERE id=198270;
UPDATE movie_keyword SET translated = '알라딘' WHERE id=198756;
UPDATE movie_keyword SET translated = '애니메이션' WHERE id=210024;
UPDATE movie_keyword SET translated = '액션히어로' WHERE id=219404;
UPDATE movie_keyword SET translated = '시력 저하' WHERE id=229046;
UPDATE movie_keyword SET translated = '디씨유니버스' WHERE id=229266;
UPDATE movie_keyword SET translated = '핸드드로잉' WHERE id=234662;
UPDATE movie_keyword SET translated = '사주살인' WHERE id=238140;
UPDATE movie_keyword SET translated = '청소년 소설' WHERE id=246466;
UPDATE movie_keyword SET translated = '창작소설' WHERE id=250164;
UPDATE movie_keyword SET translated = '추파카브라' WHERE id=254508;
UPDATE movie_keyword SET translated = '빙의' WHERE id=282933;
UPDATE movie_keyword SET translated = '사이코캘리포니아' WHERE id=301813;
UPDATE movie_keyword SET translated = '마녀 사냥꾼' WHERE id=310426;