# Generated by Django 3.2.18 on 2023-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(default='static/accounts/user.png', null=True, upload_to=''),
        ),
    ]
