# Generated by Django 3.2.18 on 2023-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
